apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: verteilte-systeme-weather-app
  name: verteilte-systeme-weather-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: verteilte-systeme-weather-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: verteilte-systeme-weather-app
    spec:
      containers:
        - image: de.icr.io/th-uni-projects/verteilte-systeme-weather-app:latest
          name: verteilte-systeme-weather-app
          resources: {}
          envFrom:
            - configMapRef:
                name: weather-app-config
            - secretRef:
                name: weather-app-secret
status: {}
