apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: verteilte-systeme-weather-app
  name: verteilte-systeme-weather-app
spec:
  ports:
    - name: 80-30922
      port: 80
      protocol: TCP
      targetPort: 30922
  selector:
    app: verteilte-systeme-weather-app
  type: NodePort
status:
  loadBalancer: {}
